id: P000498
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20189
  title: དྲག་པོ་ཡེ་ཤེས་རབ་འབར་གྱི་བསྙེན་ཡིག་དམ་པའི་ཞལ་ལུང་།
  author: ''
  volumes:
    36078fea4dfc490e9a92dca6422a9a48:
      image_group_id: I8LS20191
      title: Volume 1 of drag po ye shes rab 'bar gyi bsnyen yig dam pa'i zhal lung
        /
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
